export const COMPONENT_METADATA_KEYS = {
  EMBED_COMPONENT: 'spraxium:embed_component',
  EMBED_FIELD: 'spraxium:embed_field',
  EMBED_FIELDS_LIST: 'spraxium:embed_fields_list',
  EMBED_WHEN: 'spraxium:embed_when',
  EMBED_DESCRIPTION_FIELD: 'spraxium:embed_description_field',
  EMBED_TITLE: 'spraxium:embed_title',
  EMBED_COLOR: 'spraxium:embed_color',
  EMBED_FOOTER: 'spraxium:embed_footer',
  EMBED_TIMESTAMP: 'spraxium:embed_timestamp',
  EMBED_AUTHOR: 'spraxium:embed_author',
  EMBED_THUMBNAIL: 'spraxium:embed_thumbnail',
  EMBED_IMAGE: 'spraxium:embed_image',
  EMBED_URL: 'spraxium:embed_url',

  MODAL_COMPONENT: 'spraxium:modal_component',
  MODAL_FIELDS_LIST: 'spraxium:modal_fields_list',
  MODAL_FIELD: 'spraxium:modal_field',
  MODAL_WHEN: 'spraxium:modal_when',
  MODAL_DYNAMIC: 'spraxium:modal_dynamic',
  MODAL_DYNAMIC_FIELDS: 'spraxium:modal_dynamic_fields',
  MODAL_HANDLER: 'spraxium:modal_handler',
  MODAL_VALIDATOR: 'spraxium:modal_validator',
  MODAL_VALIDATION_CONFIG: 'spraxium:modal_validation_config',
  MODAL_FIELD_PARAM: 'spraxium:modal_field_param',
  MODAL_CACHE_CONFIG: 'spraxium:modal_cache_config',
  MODAL_TEXT_DISPLAYS: 'spraxium:modal_text_displays',
  MODAL_PENDING_CHOICES: 'spraxium:modal_pending_choices',

  SELECT_COMPONENT: 'spraxium:select_component',
  SELECT_OPTIONS_LIST: 'spraxium:select_options_list',
  SELECT_DYNAMIC_OPTIONS: 'spraxium:select_dynamic_options',
  SELECT_HANDLER: 'spraxium:select_handler',
  SELECT_SELECTED_VALUES_PARAM: 'spraxium:select_selected_values_param',

  BUTTON_COMPONENT: 'spraxium:button_component',
  BUTTON_HANDLER: 'spraxium:button_handler',

  FLOW_CONTEXT_PARAM: 'spraxium:flow_context_param',

  V2_CONTAINER: 'spraxium:v2_container',
  V2_CHILDREN: 'spraxium:v2_children',
  V2_WHEN: 'spraxium:v2_when',
} as const;
