export enum CronExpression {
  EVERY_SECOND = '* * * * * *',
  EVERY_5_SECONDS = '*/5 * * * * *',
  EVERY_10_SECONDS = '*/10 * * * * *',
  EVERY_30_SECONDS = '*/30 * * * * *',

  EVERY_MINUTE = '* * * * *',
  EVERY_2_MINUTES = '*/2 * * * *',
  EVERY_3_MINUTES = '*/3 * * * *',
  EVERY_5_MINUTES = '*/5 * * * *',
  EVERY_10_MINUTES = '*/10 * * * *',
  EVERY_15_MINUTES = '*/15 * * * *',
  EVERY_20_MINUTES = '*/20 * * * *',
  EVERY_30_MINUTES = '*/30 * * * *',
  EVERY_45_MINUTES = '*/45 * * * *',

  EVERY_HOUR = '0 * * * *',
  EVERY_2_HOURS = '0 */2 * * *',
  EVERY_3_HOURS = '0 */3 * * *',
  EVERY_4_HOURS = '0 */4 * * *',
  EVERY_6_HOURS = '0 */6 * * *',
  EVERY_8_HOURS = '0 */8 * * *',
  EVERY_12_HOURS = '0 */12 * * *',

  EVERY_DAY_AT_MIDNIGHT = '0 0 * * *',
  EVERY_DAY_AT_1AM = '0 1 * * *',
  EVERY_DAY_AT_3AM = '0 3 * * *',
  EVERY_DAY_AT_6AM = '0 6 * * *',
  EVERY_DAY_AT_9AM = '0 9 * * *',
  EVERY_DAY_AT_NOON = '0 12 * * *',
  EVERY_DAY_AT_3PM = '0 15 * * *',
  EVERY_DAY_AT_6PM = '0 18 * * *',
  EVERY_DAY_AT_9PM = '0 21 * * *',

  EVERY_WEEKDAY = '0 0 * * 1-5',
  EVERY_WEEKEND = '0 0 * * 6,0',
  EVERY_MONDAY_AT_MIDNIGHT = '0 0 * * 1',
  EVERY_TUESDAY_AT_MIDNIGHT = '0 0 * * 2',
  EVERY_WEDNESDAY_AT_MIDNIGHT = '0 0 * * 3',
  EVERY_THURSDAY_AT_MIDNIGHT = '0 0 * * 4',
  EVERY_FRIDAY_AT_MIDNIGHT = '0 0 * * 5',
  EVERY_SATURDAY_AT_MIDNIGHT = '0 0 * * 6',
  EVERY_SUNDAY_AT_MIDNIGHT = '0 0 * * 0',

  EVERY_WEEK = '0 0 * * 0',
  EVERY_1ST_OF_MONTH = '0 0 1 * *',
  EVERY_15TH_OF_MONTH = '0 0 15 * *',
  EVERY_LAST_DAY_OF_MONTH = '0 0 28-31 * *',
  EVERY_QUARTER = '0 0 1 */3 *',
  EVERY_6_MONTHS = '0 0 1 */6 *',
  EVERY_YEAR = '0 0 1 1 *',
}
