export type EnvFieldType =
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'port'
  | 'url'
  | 'email'
  | 'host'
  | 'json'
  | 'discord-token'
  | 'discord-id'
  | 'discord-webhook-url'
  | 'discord-client-secret'
  | 'discord-permissions'
  | 'mongodb-uri'
  | 'redis-uri';
