export const METADATA_KEYS = {
  MODULE: 'spraxium:module',
  INJECTABLE: 'spraxium:injectable',
  INJECT: 'spraxium:inject',
  OPTIONAL: 'spraxium:optional',
  GLOBAL: 'spraxium:global',
  LISTENER: 'spraxium:listener',
  LISTENER_EVENT: 'spraxium:listener_event',
  ON_EVENT: 'spraxium:on_event',
  ONCE_EVENT: 'spraxium:once_event',
  CTX_PARAM: 'spraxium:ctx_param',
  GUARD: 'spraxium:guard',
  GUARD_OPTION: 'spraxium:guard_option',
  USE_GUARDS: 'spraxium:use_guards',
  EXCEPTION_LAYOUT: 'spraxium:exception_layout',

  PREFIX_COMMAND: 'spraxium:prefix_command',
  PREFIX_COMMAND_HANDLER: 'spraxium:prefix_command_handler',
  PREFIX_ARG: 'spraxium:prefix_arg',
  PREFIX_ARG_PARAM: 'spraxium:prefix_arg_param',
  PREFIX_SUBCOMMAND: 'spraxium:prefix_subcommand',

  SLASH_COMMAND: 'spraxium:slash_command',
  SLASH_COMMAND_HANDLER: 'spraxium:slash_command_handler',
  SLASH_OPTION: 'spraxium:slash_option',
  SLASH_OPT_PARAM: 'spraxium:slash_opt_param',
  SLASH_FOCUSED_PARAM: 'spraxium:slash_focused_param',
  SLASH_SUBCOMMAND: 'spraxium:slash_subcommand',
  SLASH_SUBCOMMANDS_LIST: 'spraxium:slash_subcommands_list',
  SLASH_SUBCOMMAND_GROUP: 'spraxium:slash_subcommand_group',
  SLASH_SUBCOMMAND_GROUPS: 'spraxium:slash_subcommand_groups',
  SLASH_AUTOCOMPLETE_HANDLER: 'spraxium:slash_autocomplete_handler',

  EMBED_COMPONENT: 'spraxium:embed_component',
  EMBED_FIELD: 'spraxium:embed_field',
  EMBED_FIELDS_LIST: 'spraxium:embed_fields_list',
  EMBED_WHEN: 'spraxium:embed_when',
  EMBED_DESCRIPTION_FIELD: 'spraxium:embed_description_field',
  EMBED_TITLE: 'spraxium:embed_title',
  EMBED_COLOR: 'spraxium:embed_color',
  EMBED_FOOTER: 'spraxium:embed_footer',
  EMBED_TIMESTAMP: 'spraxium:embed_timestamp',
  EMBED_AUTHOR: 'spraxium:embed_author',
  EMBED_THUMBNAIL: 'spraxium:embed_thumbnail',
  EMBED_IMAGE: 'spraxium:embed_image',
  EMBED_URL: 'spraxium:embed_url',
} as const;
